server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:35432/demo-market-app?currentSchema=demo-market-app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:35432/demo-market-app?currentSchema=demo-market-app
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    encoding: UTF-8
    create-schemas: true
    schemas: demo-market-app
#logging:
#  pattern: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
#  level:
#    org.example.demomarketapp: info
#    org.example.demomarketapp.service.MainUserService: trace
#  config: /home/persi/Documents/demo-market-app/src/main/resources/logback-spring.xml
springdoc:
  webjars:
    prefix:
  swagger-ui:
    path: /demo-market-app/v3/swagger-ui.html
    disable-swagger-default-url: true
    operation-sorter: method
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
  api-docs:
    enabled: true
    path: /demo-market-app/v3/api-docs
jwt:
  secret: ihjfjfnvjofnvjerfnvjenvjernvjelrnvjervjnerjlnverjlnvjerbv
  expiration:
    minutes: 200
